# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install conda-build anaconda-client pytest pytest-cov
  - conda config --set auto_update_conda no
  - conda build conda.recipe --no-test
  - conda install --use-local tranquilizer
  - conda info -a
script:
  - pytest -v --color=yes --cov=tranquilizer tests
after_success:
  - conda install -c conda-forge codecov
  - codecov
